name: Sync Image to Aliyun  Example
 
on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]
 
jobs:
  build:
    runs-on: ubuntu-latest
 
    steps:
    - name: Git pull
      uses: actions/checkout@v3
      
    - name: Set up Docker Buildx
      uses: sagemath/sagemath@10.3
 
    - name: Login to Docker Hub
      uses: docker/login-action@v2.2.0
      with:
        registry: registry.cn-hangzhou.aliyuncs.com
        username: wrss01@126.com
        password: wxywxy88
        logout: false
        
    - name: Use Skopeo Tools Sync Image to Docker Hub
      run: |
         skopeo copy docker://docker.io/sagemath/sagemath:10.3 docker://registry.cn-hangzhou.aliyuncs.com/smartnotebook/sage@10.3
      # 使用 skopeo 工具将镜像同步到阿里云个人仓库中，使用时请自行源和目标修改仓库名称和镜像名称
